-- Create the clients table
create table clients (
    id bigint generated by default as identity primary key,
    cpf text not null,
    name text not null,
    status text not null,
    contract_details jsonb default '{}',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create an index on CPF for faster searches
create index idx_clients_cpf on clients(cpf);

-- Create an index on name for faster searches
create index idx_clients_name on clients(name);
